Feature/28 15 page 400 500
tsharon-byte/28_mf_teamwork_01 pull request #11
Opened 2023-07-24 12:24 UTC by likeariverstream

### 28-15: Вёрстка страницы ошибок 500, 400
- Страница свёрстана.
- Роут уже был добавлен, в какой то из задач.

###
[Видео](https://www.vidline.com/share/V0JBHY2LE9/3b8614e9251bf09a0365334ea44cfaf4)

2023-07-25 04:23 UTC, ioaksenenko requested changes
В целом, хорош ) Понравилось, что используешь возможности кастомизации mui на основе создания темы.

Есть что поправить:
- вынести создание темы в отдельный файл (избавиться от дублирования кода)
- подключать тему для всего приложения
- описать стили в отдельных файлах styles.module.css
- создать отдельный компонент ссылки
- убрать обработку серверных ошибок из ErrorPage (добавить роут в utils/router)
- убрать лишние зависимости, шрифты скачать и подключить из файлов

2023-07-25 04:23 UTC, ioaksenenko commented on packages/client/src/utils/router.tsx
Не забывай удалять неиспользуемые импорты.

2023-07-25 04:23 UTC, ioaksenenko commented on packages/client/package.json
Для чего нужны эти пакеты?
Если правильно понял, для использования шрифта Khand.
Думаю, лучше будет скачать шрифт, например, отсюда https://fonts.google.com/specimen/Khand.
И добавить в assets/fonts.

2023-07-26 14:46 UTC, likeariverstream commented
Исправил по замечаниям

2023-07-26 14:53 UTC, ioaksenenko approved these changes

2023-07-26 15:00 UTC, merged