added layouts
tsharon-byte/28_mf_teamwork_01 pull request #13
Opened 2023-07-25 06:33 UTC by ioaksenenko

### Какую задачу решаем
Задать основу приложения:
- навигация
- контейнеры для страниц
- набросать макеты страниц в фигме

### Выполненные задачи
1. нарисованы макеты страниц в фигме:
- Главная страница
- Страница авторизации
- Страница регистрации
- Страница 404
- Страница 5**
- Доска лидеров
Ссыка на figma: https://www.figma.com/file/tMQTrbmIiLcL3oMk4Tsya0/Untitled?type=design&node-id=0-1&mode=design&t=oXWdDnpQC8DEhCYn-0
2. Добавлены layouts:
- page-layout - для страниц с навигацией и произвольным контентом
- content-layout - для страниц с разделением контента на хедер, контент, футер (контент выделен линиями сверху и снизу согласно представленному дизайну)
3. Реализован компонент навигации.
4. Реализована домашняя страница (как пример применения page layout)
5. На странице leaderboard приведен пример применения content layout (страница реализована не полностью, т.к. для этого есть отдельная задача)
6. Добавлен компонент Title для возможности задавать заголовок с определенным шрифтом и размерном (чтобы не дублировать стили). Используется, например, на leaderboard, домашней странице.

2023-07-25 07:30 UTC, tsharon-byte requested changes
Данная работа переписывает и удаляет код других участников. Требуется обсуждение с Антоном о таких кардинальных правках

2023-07-25 07:30 UTC, tsharon-byte commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
Не очень понимаю зачем тут script добавлять

2023-07-25 07:30 UTC, tsharon-byte commented on packages/client/index.html
> +    <title>Boomberman</title>
Опечатка Bomberman

2023-07-25 07:30 UTC, tsharon-byte commented on packages/client/src/pages/home/index.tsx
> +    document.body.style.backgroundImage = 'url("home-page.png")'
Почему нельзя задать стили самому компоненту?
У меня картинка странно растягивается

2023-07-25 07:34 UTC, ioaksenenko commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
Он ведь там и был. Просто перенес его из body в head.

2023-07-25 07:36 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> +    document.body.style.backgroundImage = 'url("home-page.png")'
Картинку нужно установить в body. Ну или в #root нод. Из компонента я могу только так её установить.

2023-07-25 07:39 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> +    document.body.style.backgroundImage = 'url("home-page.png")'
Либо тут придется ещё одну обертку делать. По идее узлы header, main и footer должны быть в body. Не совсем правильно будет оборачивать это в ещё один div.

2023-07-25 07:43 UTC, ioaksenenko commented on packages/client/src/pages/registration/index.tsx
> -  const handleSubmit = () => {
Удаленную страницу вернул. Случайно вышло, после всех этих манипуляций с ветками.

2023-07-25 10:19 UTC, tsharon-byte commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
а зачем перенес?

2023-07-25 10:29 UTC, tsharon-byte commented on packages/client/src/pages/home/index.tsx
> +    document.body.style.backgroundImage = 'url("home-page.png")'
Можно сделать обертку, для нее прописать свойства страницы
background-image или max-width
В этом и есть смысл задачки на Layout чтобы сверстать основной шаблон для страницы.
В  React приложении мы напрямую с body не взаимодействуем, только с `#root`

2023-07-25 11:56 UTC, ioaksenenko commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
Хотел добавить в body id="root", чтобы layout рендерил header, main и footer в body, а не в <div id="root">.
Поэтому перенес скрипт из body, чтобы он не удалился при перерендеринге.
Но потом понял, что это не очень хорошее решение. Поэтому не стал так делать. Но скрипт оставил в header. Разве это ошибка?

2023-07-25 12:03 UTC, tsharon-byte commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
Скрипт работающий с разметкой должен быть перед закрывающим тегом </body>

2023-07-25 12:55 UTC, tsharon-byte requested changes
<img width="955" alt="image" src="https://github.com/tsharon-byte/28_mf_teamwork_01/assets/58146989/a84f0643-f906-4652-bbb8-ae371aca851d">
У меня верстка некорректно отображается

2023-07-25 12:55 UTC, tsharon-byte commented on packages/client/src/pages/home/index.tsx
> +        <Title>Boomberman</Title>
Bomberman

2023-07-25 12:55 UTC, tsharon-byte commented on packages/client/src/layouts/page-layout/styles.module.css
> +}
Нужно добавить
.header {
    position: relative;
}
Чтобы работало 
`position: fixed` для навигации

2023-07-25 12:55 UTC, tsharon-byte commented on packages/client/src/index.css
> +body,
Здесь стили для body не нужны, т.к. мы работаем напрямую с `#root`

2023-07-25 12:55 UTC, tsharon-byte commented on packages/client/src/index.css
> -  background: #171813;
Пример стилей для `#root`
`font-family: 'Inter', Arial, sans-serif;
  background: #171813;
  -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -moz-text-size-adjust: 100%;
    text-rendering: optimizeLegibility;`
    
    Все остальное здесь не нужно.
    Напр height и width задастся напрямую в page

2023-07-25 12:55 UTC, tsharon-byte commented on packages/client/src/pages/home/styles.module.css
> +.page {
Предлагаю класс назвать например `page_type_home`
т.к. класс page с описание общих свойст для лэйаута уже существует
Кроме того данный класс должен содержать только специфичные свойства, например 
background-image: url('home-page.png');
  background-repeat: no-repeat;
  background-size: cover;

2023-07-25 13:02 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> +        <Title>Boomberman</Title>
Это уже исправлено

2023-07-25 13:05 UTC, ioaksenenko commented on packages/client/src/layouts/page-layout/styles.module.css
> +}
А зачем position fixed у навигации? У нас ведь не лендинг. Скрулинга нет.

2023-07-25 13:09 UTC, ioaksenenko commented on packages/client/src/index.css
> -  background: #171813;
Да, в целом все стили, что сейчас прописаны для #root задаются сейчас в page. Поэтому могу вообще удалить эти стили для #root.

2023-07-25 13:15 UTC, ioaksenenko commented on packages/client/src/index.css
> +body,
Убрал стили для body

2023-07-25 13:16 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> +    document.body.style.backgroundImage = 'url("home-page.png")'
Добавил обертку

2023-07-26 07:16 UTC, tsharon-byte commented on packages/client/index.html
> +    <script defer type="module" src="/src/main.tsx"></script>
Предлагаю оставить как было тогда

2023-07-26 08:09 UTC, tsharon-byte requested changes

2023-07-26 08:09 UTC, tsharon-byte commented on packages/client/src/pages/login/styles.module.css
>    color: #fff;
Имеет смысл здеть прописывать цвет если он уже прописан у нас в теме?

2023-07-26 08:31 UTC, ioaksenenko commented on packages/client/src/pages/login/styles.module.css
>    color: #fff;
Эти стили добавлял не я. Поэтому вопрос не ко мне.
Они были добавлены в рамках доработки формы авторизации, регистрации. Сейчас они есть в main ветке, можешь глянуть.

2023-07-26 08:37 UTC, ioaksenenko commented on packages/client/src/pages/home/styles.module.css
> +  top: 128px;
Сейчас не уезжает. По крайней мере мне не удается воспроизвести этот кейс.

2023-07-26 08:39 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> -        </Link>
Правила игры вернул

2023-07-26 08:43 UTC, ioaksenenko commented on packages/client/src/pages/home/styles.module.css
> +.page {
Убрал лишние правила. Остальные нужны.

2023-07-26 16:06 UTC, tsharon-byte approved these changes

2023-07-27 00:47 UTC, merged