28-17 Реализовать логику авторизации
tsharon-byte/28_mf_teamwork_01 pull request #14
Opened 2023-07-25 13:18 UTC by Avanire

### Какую задачу решаем

Пользователь не может зайти ни на какую страницу проекта, если он не авторизован.

2023-07-26 01:40 UTC, ioaksenenko requested changes
Хорошая работа, молодец )
Есть несколько некритичных замечаний. Самое основное:
- по возможности описать api классами и добавить контроллеры (как это делали в первом модуле)
- убрать лишний код из handleSubmit
- возможно стоит использовать axios вместо fetch
Подробное описание смотри ниже.

2023-07-26 01:40 UTC, ioaksenenko commented on packages/client/src/pages/registration/index.tsx
Тут замечания такие же, как и к странице login. С 1 по 3 пункт.

2023-07-26 01:40 UTC, ioaksenenko commented on packages/client/src/utils/type.ts
1. Если разделить api по файлам, можно было бы перенести типы ближе к месту, где они используются.
2. В данном случае лучше бы использовать interface вместо type.
3. Можно обсудить внутри команды и определиться, как лучше именовать типы. Я просто привык добавлять к типу префикс I, если это интерфейс и T, если это тип. У тебя смотрю префиксы не используются. В целях сохранения стиля нужно будет решить, как всё-таки будем именовать и исправить, там где это необходимо.
4. И ещё наверное сам файл лучше переименовать в types. Там же много типов может быть описано.

2023-07-26 11:39 UTC, Avanire commented on packages/client/src/pages/login/index.tsx
2. Ты именно про контроллеры или про апи на классах? В контроллере я не вижу смысла тут. Дальше, я думаю, у нас появится какой нибудь стейтменеджер и логику обращения к апи уже будет в нем. Если ты имеешь ввиду про структуру класса, то мы вроде как отказались от нее, а кроме структуры ничего не изменится. 
3. Не разобрался с начала как ты реализовал, ты в своем роде сделал мидлвеар, но вернуть в onSubmit что то кроме event  я не могу тк тыы унаследовался от FormHTMLAttributes<HTMLFormElement>. И второе, где то потребуется json, где то formdata - те возвращать оба параметра, не особо красиво, как по мне. Да в моем варианте больше кода, но понятно что происходит на уровне функции и не надо искать связи.

2023-07-26 11:42 UTC, Avanire commented on packages/client/src/utils/api.ts
1. Почему не использовал классы написал выше, если вопрос в том чтобы создать отдельные файлы под разные апи, то можно выделить отдельно функции get/post/delete и отдельно сделать файлы с запросами непосредственно к апи. Согласен так будет удобней

2023-07-26 11:43 UTC, Avanire commented on packages/client/src/utils/type.ts
2. Как ты определяешь интерффейс или тип?

2023-07-27 01:31 UTC, ioaksenenko commented on packages/client/src/pages/login/index.tsx
2. Вообще по-хорошему надо бы и API сделать на классах и добавить контроллеры. Когда добавится стейтменеджер, ничего не изменится. Можно просто методы контроллера использовать как redux thunk функции. Например,
`dispatch(forumController.createTopic(data))`. Внутри createTopic можно запустить loader `dispatch(runLoading())`, вызвать `forumTopicAPI.create(data)` на успех сделать, например `dispatch(addFoumTopic(response.data))`, если ошибка `dispatch(setError(response.data))`.
По поводу структуры класса ты наверное имеешь в виду, что мы решили писать компоненты не на классах, а на функциях. Но это не значит, что классы теперь нельзя использовать в проекте. Например, валидаторы и правила валидации я сделал на классах. Благодаря наследованию и другим преимуществам ООП, код получился чистым, компактным и масштабируемым.
3. Можно тогда хотя бы оформить получение данных из формы в json формате в виде хелпер-функции и вызывать её в компоненте Form и в твоем handleSubmit. Чтобы было меньше дублирования и упростить поддержку в дальнейшем.

2023-07-27 01:32 UTC, ioaksenenko commented on packages/client/src/utils/api.ts
Решай сам, конечно, но я бы лучше всё же на классах сделал.

2023-07-27 01:35 UTC, ioaksenenko commented on packages/client/src/utils/type.ts
Я обычно интерфейс использую для описания объекта, а тип только для комбинации других типов или интерфейсов. Например,

interface IExample1 { ... }
interface IExample2 { ... }

type TAllExamples = IExample1 | IExample2

или, напрмер, когда нужно описать тип функции

type TCallback = () =>void

2023-07-27 01:42 UTC, ioaksenenko approved these changes
Критичных замечаний нет.
Но архитектурно будет лучше решение на классах. Если есть время поправить, лучше бы поправить.

2023-07-27 20:49 UTC, IvanPeleshok commented on packages/client/src/pages/login/index.tsx
> +    login(data)
Предлагаю **во всём PR** заменить callback-и then / catch на async / await + try / catch
Пример: https://stackoverflow.com/questions/44663864/correct-try-catch-syntax-using-async-await#:~:text=Actually%20I%27d%20say%20it%20is.%20You%20usually%20want%20to%20catch%20all%20exceptions%20from%20working%20with%20the%20value%3A
Плюсы: пишем плоский код, другие разработчики будут счастливы читать твой код

2023-07-27 20:55 UTC, IvanPeleshok commented on packages/client/src/components/protected-route/index.tsx
> +  getUser().catch(() => {
async / await + try / catch

2023-07-27 20:56 UTC, IvanPeleshok commented on packages/client/src/pages/registration/index.tsx
> +    registration(data)
async / await + try / catch

2023-07-27 20:56 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +  return axios({
async / await + try / catch

2023-07-27 20:56 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +}
Не хватает отступа

2023-07-27 20:56 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +export const getRequest = (
Не хватает отступа

2023-07-27 20:57 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +}
Не хватает отступа

2023-07-27 20:57 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +export const deleteRequest = (
Не хватает отступа

2023-07-27 21:05 UTC, IvanPeleshok commented on packages/client/src/utils/http-transport/index.ts
> +
Предлагаю ознакомиться со статьёй: https://rapidapi.com/guides/custom-axios-instance
Можно поискать ещё примеры
```
const instance = axios.create({
	baseURL: 'https://....',
  withCredentials: true,
});


const getQuotes = async (body: IBody) => {
	return instance .post('/user/create', body)
};
```
Лучше один раз сконструировать экземпляр axios и потом прокидывать отдельные параметры

2023-07-27 21:11 UTC, IvanPeleshok commented on packages/client/src/utils/constants.ts
> +export const API_URL = 'https://ya-praktikum.tech/api/v2'
Предлагаю переменную вынести в переменные окружения (process.env)

2023-07-27 21:21 UTC, IvanPeleshok requested changes
Замечательно, что написаны тесты
Есть замечания

2023-07-30 21:54 UTC, IvanPeleshok commented on packages/client/src/api/auth-api/index.ts
> +export const registration = async (data: TRegistrationData) => {
Для какой цели async? (не используется await, получается избыточно)

2023-07-30 21:57 UTC, IvanPeleshok commented on packages/client/src/components/protected-route/index.tsx
> +  getUser().catch(() => {
async / await + try / catch

2023-07-30 21:58 UTC, IvanPeleshok requested changes
Небольшие замечания

2023-07-30 22:02 UTC, IvanPeleshok commented on packages/client/src/api/auth-api/index.ts
> +  return axiosInstance.post('auth/signup', data)
Описать тип, который будет возвращать ответ
Если не ошибаюсь, то дженерик в данном случае должен быть описан следующим образом: 
```
axiosInstance.post<IResponse>(url, body)
```

2023-07-31 07:37 UTC, IvanPeleshok commented on packages/client/src/components/protected-route/index.tsx
> +    ;(async () => {
; видимо лишний
Рекомендация: когда будете переходить на redux / mobx и т.д, перепишите данную функцию, чтобы она не вызывалась ананонимно
```
const  request = async () => {
  await getSome()
}
request()
```

2023-07-31 07:38 UTC, IvanPeleshok approved these changes

2023-07-31 10:53 UTC, merged