28-37 Добавлен Service Workers
tsharon-byte/28_mf_teamwork_01 pull request #19
Opened 2023-08-02 12:07 UTC by Avanire

### Какую задачу решаем

Приложение должно попадать в кеш при первой загрузке и после этого загружаться без интернета — не только элементы входа и пользовательские настройки, но и сама игра.

2023-08-03 14:12 UTC, tsharon-byte approved these changes
Хорошая работа, в соответствии с заданием
Из недостатков можно выделить следующее:
 - сама игра не кэшируется
  - ветка устарела и не содержит фиксов с ветки main
   - см. комментарии к коду

2023-08-03 14:12 UTC, tsharon-byte commented on packages/client/service-worker.ts
> +      .open(`${version}${cacheName}`)
Может имеет смысл вынести в константу `${version}${cacheName}` так как это используется всегда вместе и одинаково в разных местах?

2023-08-03 14:12 UTC, tsharon-byte commented on packages/client/service-worker.ts
> +const URLS = ['/index.html', '/src/main.tsx']
Сама игра не кэшируется

2023-08-03 14:55 UTC, Avanire commented on packages/client/src/utils/service-worker/startServiceWorker.ts
> +          console.log(res)
Дебажил забыл поправить, уберу

2023-08-03 14:56 UTC, Avanire commented on packages/client/service-worker.ts
> +      .then((cache: Cache) => cache.addAll(URLS))
Сделаю рефакторинг, думаю будет лучше

2023-08-03 15:49 UTC, Olegas requested changes
Добрый день.
Сейчас, судя по коду, ServiceWorker рассчитан только на отладочную версию приложения. Т.к. в коде зашиты имена файлов, которые отсутствуют в релизной сборке.
Нужно доработать

2023-08-03 15:49 UTC, Olegas commented on packages/client/service-worker.ts
> +const URLS = ['/index.html', '/src/main.tsx']
А разве в продакшен-сборке в приложении останется файл с расiирением tsx?

2023-08-06 07:52 UTC, Olegas approved these changes
Отлично! Работа принята

2023-08-07 01:44 UTC, merged