added redux
tsharon-byte/28_mf_teamwork_01 pull request #21
Opened 2023-08-03 03:47 UTC by ioaksenenko

### Какую задачу решаем
1. Добавить в проект redux-toolkit.
2. Добавить слайс для юзера (к примеру).
3. После авторизации класть информацию о юзере в слайс.

2023-08-03 13:41 UTC, tsharon-byte approved these changes
Хорошая работа, корректно добавлен слайс для пользователя.
Предложения по доработке:
 - Сейчас отсутствует возможность логаута. поэтому нет возможности протестировать работу хранилища при логине/логауте
  - сейчас непонятно что будет с случае ошибки получения пользователя - редирект на экран 500?
   - можно сделать инициализацию хранилища из localStorage
    - заметила что после перехода с главной страницы на страницу лидерборда, 2раза запрашивается пользователь, хотя вроде не должен т.к. в хранилище уже есть

2023-08-03 13:41 UTC, tsharon-byte commented on packages/client/src/components/auth/index.tsx
> +    <Avatar
Нет возможности выйти из аккаунта

2023-08-03 13:41 UTC, tsharon-byte commented on packages/client/src/store/slices/user-slice/types.ts
> +  display_name: string
Вроде бы поле display_name необязательное, в отличие от остальных полей

2023-08-04 05:03 UTC, ioaksenenko commented on packages/client/src/store/slices/user-slice/types.ts
> +  display_name: string
Согласен. Но пока что так оставлю, чтобы не пришлось в mockData для leaderboard вносить кучу данных, которые на этой странице не используются.

2023-08-04 05:04 UTC, ioaksenenko commented on packages/client/src/components/auth/index.tsx
> +    <Avatar
Добавил возможность перехода на страницу профиля и там есть кнопка выхода.

2023-08-04 05:20 UTC, tsharon-byte approved these changes

2023-08-04 12:16 UTC, IvanPeleshok commented on packages/client/src/components/auth/index.tsx
> +  return loading ? (
Слишком сложный тернарник получается, такое читать достаточно сложно
Предлагаю следующий подход
```
if (loading) {
  return <CicularProgress />
}

return user
  ? JSX
   : JSX
```

2023-08-04 12:18 UTC, IvanPeleshok commented on packages/client/src/hooks/use-auth/index.ts
> +    loginRequest(data)
Давай перепишем на async / await + try / catch (плоский код всегда намного приятнее читать)

2023-08-04 12:22 UTC, IvanPeleshok commented on packages/client/src/hooks/use-auth/index.ts
> +            break
Для того, чтобы не дублировать break в каждом случае, можно вернуть вызов функции
```
switch (response.status) {
  case 200:
    return navigate(ROUTE_PATH.HOME)
}
```

2023-08-04 12:23 UTC, IvanPeleshok commented on packages/client/src/store/slices/user-slice/thunks/retrieve-user-thunk/index.ts
> +    axiosInstance
async / await + try / catch

2023-08-04 12:24 UTC, IvanPeleshok requested changes
Есть замечания

2023-08-05 11:20 UTC, IvanPeleshok approved these changes
Замечательная работа

2023-08-05 12:48 UTC, merged