28-23: Страница профиля
tsharon-byte/28_mf_teamwork_01 pull request #23
Opened 2023-08-06 20:42 UTC by likeariverstream

### Какую задачу решаем
1. Сверстать страницу профиля.
2. Подключить API смены пароля.
3. Сверстать компонент изменения аватара.
4. Подключить API для смены аватара пользователя.

### Скриншоты/видяшка (если есть) 
[WEB_2023-08-07_03:31](https://www.vidline.com/share/V085H21MY6/bbd92b4aa73a4d78804e07dcac471d13)
### TBD (если есть)

2023-08-07 02:24 UTC, ioaksenenko approved these changes
Проделана большая работа. Молодец, хорошо справился.
Есть несколько некритичных замечаний, которые желательно исправить, как будет время.

2023-08-07 02:24 UTC, ioaksenenko commented on packages/client/src/store/slices/user-slice/thunks/change-password-thunk/index.ts
Думаю, для error лучше описать тип где-нибудь в файле types. Как-то громоздко получилось.

2023-08-07 02:24 UTC, ioaksenenko commented on packages/client/src/store/slices/user-slice/index.ts
Мне кажется это лучше внутри thunk делать
```typescript
if (action.payload === 'Password is incorrect') {
          state.error = 'Введен неверный пароль'
        } else {
          state.error = 'Произошла ошибка'
        }
```
А в редьюсере просто установить в state.error = payload

2023-08-07 02:24 UTC, ioaksenenko commented on packages/client/src/pages/profile/index.tsx
Если не ошибаюсь, то при таком определении callbacks при изменении хотя бы одного callback, у тебя изменится вся переменная callbacks, а значит обновятся все компоненты, которые от нее зависят. То есть обновятся все компоненты, которые принимают коллбеки, а не только тот, чей коллбек реально изменился. То есть тут получается немного не оптимально. Думаю лучше каждый коллбек определять в отдельной переменной.

2023-08-07 02:31 UTC, ioaksenenko commented on packages/client/src/components/profile-components/profile-info/index.tsx
Вот тут ещё хотел отменить, что не понятно, для каких данных это поле если оно не заполнено
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/2d025e42-fd7e-4f82-90ae-23bf5c501375)

2023-08-07 02:33 UTC, ioaksenenko commented on packages/client/src/components/profile-components/profile-info/index.tsx
И ещё можно добавить сюда такие поля как first_name, second_name, phone.

2023-08-07 06:20 UTC, tsharon-byte approved these changes

2023-08-07 10:55 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-info/index.tsx
Добавил поля

2023-08-07 10:55 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
Там вроде зависимостей не хватало, добавил)

2023-08-07 10:55 UTC, likeariverstream commented on packages/client/src/store/slices/user-slice/index.ts
Исправил, перенес в thunk

2023-08-07 10:56 UTC, likeariverstream commented on packages/client/src/store/slices/user-slice/thunks/change-password-thunk/index.ts
Добавил интерфейс

2023-08-07 10:56 UTC, likeariverstream commented on packages/client/src/components/text-field/index.tsx
Исправил

2023-08-07 10:56 UTC, likeariverstream commented on packages/client/src/components/profile-components/styled-edit-icon/index.tsx
Перенес в src/icons

2023-08-07 10:58 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-info/index.tsx
1. Кнопки редактирования пока работать не будут, т.к. это не входит в текущую задачу, добавил пока возможность просто вводить значение в инпут)
2. Создал компонент EditTextField
3. Эту кнопку тоже вынес в отдельный компонент

2023-08-07 10:58 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/types.ts
Исправил оба замечания

2023-08-07 11:03 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
1. Перенес стили
2. Записал пропсы развернуто
3. Исправил
4, 6. Убрал Box, но для стилизации с помощью темы пока пришлось добавить div - иначе получал ошибку в консоли, что неверный элемент
5. Изменил верстку модалки)

2023-08-08 04:21 UTC, ioaksenenko approved these changes
Отличная работа, код и ui стал значительно лучше.

2023-08-08 04:21 UTC, ioaksenenko commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
Круто, молодец.
По третьему пункту можно как вариант форму обернуть в forwardRef, тогда ошибки не будет.

2023-08-08 04:21 UTC, ioaksenenko commented on packages/client/src/components/profile-components/profile-info/index.tsx
По первому пункту разве не входит в эту задачу? Это ведь тоже относится к странице профиля.
Надо тогда создать связанную подзадачу в linear.

2023-08-08 04:21 UTC, ioaksenenko commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
Есть ещё небольшие замечания:
1. При клике на иконку редактирования нужно, чтобы инпут получал фокус и менялась иконка с карандаша на галочку, например. Чтобы было понятно, что поле стало редактируемым. Сейчас оно никак не меняется. Со стороны UI не понятно, что его можно редактировать после клика на карандаш.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/4846c61a-27be-4cde-a699-6d03ffcd4458)
2. Надо бы добавить label в инпуты, чтобы когда поле пустое было понятно, какие данные там нужно ввести. Сейчас если поле не заполнено - не понятно
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/256764f2-13f3-4003-9177-ae8fb49ce2da)
3. Заголовок модалки лучше сделать h5. body1 как-то маловат
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/0291eea9-6f8f-410f-86bc-80d32d4b9ef9)

2023-08-08 04:21 UTC, ioaksenenko commented on packages/client/src/pages/profile/index.tsx
Не, я вообще про то, что все коллбеки в одной переменной.
```typescript
const callbacks = {
callback1: (...) => ...
callback2: (...) => ...
...
}
```
Мне кажется лучше так
const callback1 = (...) => ...
const callback2 = (...) => ...

2023-08-08 04:59 UTC, ioaksenenko commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
Ещё предлагаю цвет overlay поменять
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/ddef8b3d-f340-4012-bf82-b14287eb43ab)
Черный сливается с задним фоном

2023-08-08 21:07 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
1. Добавил фокус и смену иконки
2. Добавил лэйблы
3. Изменил заголовок на h5
А также обернул форму в forwardRef

2023-08-08 21:07 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-info/index.tsx
Не входит, я на бэклог ориентируюсь) Задача по подключению  API изменения остальных профиля будет позже

2023-08-08 21:07 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
Понял) исправил

2023-08-09 00:22 UTC, ioaksenenko approved these changes
Отличная работа! Замечаний нет.

2023-08-09 10:00 UTC, tsharon-byte commented on packages/client/src/components/profile-components/change-password-modal/styles.module.css
> +.modal__close_button {
Некорректное именование по БЭМ.

2023-08-09 10:00 UTC, tsharon-byte commented on packages/client/src/components/profile-components/change-password-modal/styles.module.css
> +.modal__close_button:hover {
Некорректное именование по БЭМ.

2023-08-09 10:05 UTC, tsharon-byte commented on packages/client/src/components/profile-components/profile-header/index.tsx
> +    <header className={styles.profile__header}>
Здесь `<header>` избыточный таг
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/58146989/ca7a0a39-ba99-43d7-9e82-6c2ca982f3cc)

2023-08-09 10:09 UTC, tsharon-byte commented on packages/client/src/components/profile-components/profile-header/styles.module.css
> +  padding: 52px 29px 60px 29px;
Почему такие отступы? у меня кнопка сливается с горизонтальной линией
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/58146989/6202304d-ddab-4fff-b03d-3b9c43b7f19e)

2023-08-09 10:20 UTC, tsharon-byte commented on packages/client/src/components/profile-components/profile-header/index.tsx
> +    <header className={styles.profile__header}>
Нашла в чем проблема - некорректно организован лэйаут: PageLayout уже содержит блоки `header` и `footer` 
А внутри ContentLayout создаются дополнительные header и footer

2023-08-09 17:29 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду.
Написал их в комментариях.

2023-08-09 17:29 UTC, Olegas commented on packages/client/src/components/profile-components/change-password-modal/types.ts
> +  hanldeCloseModal: () => void
Опечатка в слове handle

2023-08-09 17:29 UTC, Olegas commented on packages/client/src/components/profile-components/edit-text-field/index.tsx
> +          textFieldRef.current.focus()
Точно ли нужно всегда фокусироваться? Разве не только в том случае, когда мы переходим в режим редактирования?

2023-08-09 17:29 UTC, Olegas commented on packages/client/src/components/profile-components/profile-avatar/index.tsx
> +      user,
Нужно ли выставлять наружу обработчики событий и признак isHover? Очень странное API. Почему кто-то снаружи решает, находится аватар под курсором мыши или нет? Куда лаконичнее будет, если компонент сам внутри себя решит эти вопросы.

2023-08-11 08:19 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-avatar/index.tsx
> +          <DeleteOutlineIcon
Его пока не будет, т.к. непонятно, какой должен быть обработчик

2023-08-11 08:20 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-info/index.tsx
> +    <>
Добавил форму и событие с валидацией

2023-08-11 08:20 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
> +  const handleSubmit = useCallback(() => {
Переименовал

2023-08-11 08:20 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
> +    dispatch(changePasswordThunk(password))
Добавил функционал - модалка будет закрываться при успешном сабмите

2023-08-11 08:20 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
> +      <Modal open={isOpenModal} onClose={hanldeCloseModal}>
Исправил

2023-08-11 08:20 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
> +        hanldeCloseModal={hanldeCloseModal}
исправил

2023-08-11 08:51 UTC, likeariverstream commented on packages/client/src/pages/profile/index.tsx
> +  const [isOpenModal, setIsOpenModal] = useState(false)
Тут что то не соображу как без редакса обойтись)

2023-08-11 08:51 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/styles.module.css
> +.modal__text_field {
Это не БЭМ, исправил названия)

2023-08-11 08:51 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-header/index.tsx
> +    <header className={styles.profile__header}>
Это так. А почему не может быть два хэдера на странице?)

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-header/styles.module.css
> +  padding: 52px 29px 60px 29px;
Изменил стили

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/icons/styled-edit-icon/index.tsx
> +        target.style.cursor = 'pointer'
Исправил

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/types.ts
> +  hanldeCloseModal: () => void
исправил

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/types.ts
> +  handleSubmit: () => void
даннные о пароле получает от родителя, а событие наверное нужно, исправил

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/edit-text-field/index.tsx
> +          textFieldRef.current.focus()
Исправил)

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-avatar/index.tsx
> +      user,
Изменил, перенес в компонент

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-avatar/index.tsx
> +          }}
Убрал sx

2023-08-11 08:52 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-header/index.tsx
> +        }}
Исправил

2023-08-11 08:53 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/styles.module.css
> +.modal__close_button:hover {
Исправил названия

2023-08-11 09:54 UTC, tsharon-byte commented on packages/client/src/pages/profile/index.tsx
> +  const [isOpenModal, setIsOpenModal] = useState(false)
Можно пока так оставить, просто для информации

2023-08-11 10:34 UTC, tsharon-byte commented on packages/client/src/components/profile-components/profile-header/index.tsx
> +    <header className={styles.profile__header}>
Какой смысл размещать блок `<header>` внутри блока `<main>`? 
Разметка в документе должна быть корректно организована, например для конкретной работы скринридеров.
Я так понимаю, что ты не до конца разобрался с лэйаутами которые придумал Иван.
Смотри: получается так
PageLayout состоит из 3-х логических блоков
`<header>` с навигацией сайта
`<main>` основная информация страницы
`<footer>` подвал сайта

Блок `<main>` может еще быть разделен на 3 части горизонтальными линиями: заголовок, содержимое.
Твоя навигация - кнопочка Back является навигацией или заголовком основного содержимого?

2023-08-11 10:35 UTC, tsharon-byte approved these changes

2023-08-11 16:36 UTC, Olegas approved these changes
Отлично, работа принята!

2023-08-12 00:55 UTC, merged