28-25: Экран завершения игры
tsharon-byte/28_mf_teamwork_01 pull request #25
Opened 2023-08-07 18:45 UTC by likeariverstream

###Сверстать экран завершения игры

### Титульная надпись страницы и две ссылки - "Повторить" и "Вернуться в главное меню"

2023-08-08 04:40 UTC, ioaksenenko approved these changes
Хорошая работа. Есть небольшие замечания.

2023-08-08 04:40 UTC, ioaksenenko commented on packages/client/src/pages/end-game/index.tsx
А зачем фрагмент? Можно так
```typescript
const EndGame: FC = () => (
  <ContentLayout navigation={false}>
    <EndGameTitle text="Игра завершена" />
    <EndGameLink>
      <StyledLink text="Повторить" to="/game" />
      <StyledLink text="Вернуться на главную страницу" to="/" />
    </EndGameLink>
  </ContentLayout>
)
```

2023-08-08 04:40 UTC, ioaksenenko commented on packages/client/src/pages/end-game/index.tsx
Предлагаю такой вариант. Картинку можно другую поставить, как вариант, чтобы не совпадала с 404.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/f364fef4-8183-4af8-a300-6ffa8aefd57e)

2023-08-08 04:40 UTC, ioaksenenko commented on packages/client/src/pages/end-game/index.tsx
А когда мы попадаем на эту страницу? Сейчас вроде просто сообщение выводится
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/cd42fa1f-e780-4827-8802-f55032046c75)

2023-08-08 12:55 UTC, tsharon-byte commented on packages/client/src/pages/end-game/index.tsx
Да, алерт был как заглушка пока писался сам экран завершения игры
На самом деле вариантов завершения игры 2 - игрок проиграл
и нашел портал - выиграл. В случае выигрыша нужно показывать счет например, который используется в дальнейшем для лидерборда.
Думаю нужно сейчас добавить редирект на эту страницу в случае успеха/неуспеха

2023-08-08 21:56 UTC, likeariverstream commented on packages/client/src/pages/end-game/index.tsx
И верно) Состояние завершения игры решается в другой задаче, 28-35
Удалил ненужный фрагмент и добавил картинку (пока как на скрине)

2023-08-09 00:27 UTC, ioaksenenko approved these changes
Всё круто, замечаний нет )

2023-08-09 07:55 UTC, tsharon-byte requested changes

2023-08-09 07:55 UTC, tsharon-byte commented on packages/client/src/pages/end-game/index.tsx
> +const Image = styled('img')({})
Предлагаю явно задать высоту картинки здесь, На моем экране картинка очень большая, поэтому все содержимое слезает вниз, например
`const Image = styled('img')({ height: '100px' })`

2023-08-09 07:55 UTC, tsharon-byte commented on packages/client/src/components/end-game-components/end-game-title/styles.module.css
> +  font-size: 128px;
Стили переопределяются стандартными и подключаются некорректно
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/58146989/e2f18ebe-d877-4170-b5b7-6cd9fe71b3bc)

2023-08-10 12:53 UTC, likeariverstream commented on packages/client/src/components/end-game-components/end-game-title/styles.module.css
> +  font-size: 128px;
Исправил

2023-08-10 12:53 UTC, likeariverstream commented on packages/client/src/pages/end-game/index.tsx
> +const Image = styled('img')({})
Изменил на 100px

2023-08-10 15:34 UTC, tsharon-byte approved these changes

2023-08-10 15:34 UTC, tsharon-byte commented on packages/client/src/components/end-game-components/end-game-title/styles.module.css
> +  font-family: Notable !important;
Предлагаю стили класса убрать, и прописать стандартные для варианта h1, т.к. заголовок стандартный как на всех страницах
const darkTheme = createTheme({
  typography: {
    h1: {
      color: '#FFFFFF',
      fontFamily: 'Notable',
      fontSize: '128px',
      fontWeight: 400,
      padding: 16,
    },
  },

2023-08-10 16:29 UTC, likeariverstream commented on packages/client/src/components/end-game-components/end-game-title/styles.module.css
> +  font-family: Notable !important;
Это заголовок для страницы завершения игры, компонент <EndGameTitle />..)

2023-08-10 16:33 UTC, likeariverstream commented on packages/client/src/components/end-game-components/end-game-title/styles.module.css
> +  font-family: Notable !important;
Добавил в тему)

2023-08-10 17:24 UTC, merged