28-18 Страница форума
tsharon-byte/28_mf_teamwork_01 pull request #29
Opened 2023-08-12 12:05 UTC by likeariverstream

### Вёрстка страницы форума

- функционал создания топика,
- экран со всем топиками,
- экран одного топика с комментами,
- функциональность добавления комментария к топику.
API будет написана в 8м спринте

2023-08-13 03:20 UTC, ioaksenenko approved these changes
Проделана большая работа. Молодец, хорошо справился.
Критичных замечаний нет. Топики создаются, комментарии в топиках создаются.

Пока что не сохраняются комментарии в топиках, нужно будет доработать в дальнейшем. Возможно выделить отдельную подзадачу.
Так же можно добавить дополнительный функционал, вроде поиска по темам топика, фильтры. Функционал для ответа на конкретный комментарий топика. Можно поправить дизайн (набросал в фигме вариант https://www.figma.com/file/tMQTrbmIiLcL3oMk4Tsya0/Bomberman?type=design&node-id=0-1&mode=design&t=IfRJUoHgBbXaT3nd-0).
Есть несколько некритичных замечаний по коду.

2023-08-13 03:20 UTC, ioaksenenko commented on packages/client/src/store/slices/forum-slice/index.ts
1. Мне кажется лучше вынести interface в types.
2. Для типизации action лучше использовать PayloadAction.

2023-08-13 03:20 UTC, ioaksenenko commented on packages/client/src/store/slices/forum-slice/thunks/create-chat-thunk/index.ts
Можно возвращать конкретную причину неудачного создания, если она есть
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/fefbe78c-2c92-4da0-a148-dae68bb2f49f)
и статус ошибки. По хорошему бы ещё отслеживать, какая произошла ошибка и если 500-я ошибка лучше бы перенаправлять на page-500.
Можешь посмотреть пример в retrieve-user-thunk.

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/components/icons/close-icon/styles.module.css
Использовал IconButton

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/components/profile-components/change-password-modal/index.tsx
Использовал

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/components/topic-components/topic-comments-layout/index.tsx
Исправил

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/constants/urls.ts
Исправил

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/pages/forum/index.tsx
Хук добавил) по дизайну позже внесу исправления

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/store/slices/forum-slice/index.ts
Исправил оба пункта

2023-08-14 07:19 UTC, likeariverstream commented on packages/client/src/store/slices/forum-slice/thunks/create-chat-thunk/index.ts
Исправил)

2023-08-14 08:30 UTC, tsharon-byte requested changes
Необходимо исправить хук useChats

2023-08-14 08:30 UTC, tsharon-byte commented on packages/client/src/hooks/use-chats/index.ts
> +    if (chats.length === 0) {
У меня сейчас чатов 0, поэтому страница зависает в бесконечном цикле по загрузке чатов. Возможно имеет смысл запрашивать список чатов только при монтировании компонента?

2023-08-14 08:50 UTC, likeariverstream commented on packages/client/src/hooks/use-chats/index.ts
> +    if (chats.length === 0) {
исправил

2023-08-15 09:00 UTC, Olegas approved these changes
Работа принята. Есть одно небольшое замечание-совет.

2023-08-15 10:14 UTC, likeariverstream commented on packages/client/src/pages/forum/index.tsx
> +  const handleOpenModal = () => setIsOpenModal(true)
И верно) Исправлю это

2023-08-15 11:52 UTC, ioaksenenko commented on packages/client/src/components/forum-components/create-topic-modal/index.tsx
Я бы всё же предложил переименовать поле на "Название темы" (чтобы не повторялось название модалки и название поля) и не делать focused по умолчанию
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/00387ad6-c5c3-4525-a5c0-659686782dc3)

2023-08-15 11:53 UTC, ioaksenenko commented on packages/client/src/components/forum-components/create-topic-modal/index.tsx
И ещё кажется тут лишние отступы
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/7699c6ca-5732-48bd-8536-bb60e2738fa2)

2023-08-15 12:02 UTC, ioaksenenko commented on packages/client/src/constants/urls.ts
Вот этот тогда лишний url
```typescript
export const RETRIEVE_CHATS_URL = 'chats/'
```

2023-08-16 00:31 UTC, ioaksenenko approved these changes

2023-08-16 07:11 UTC, tsharon-byte approved these changes

2023-08-16 07:20 UTC, merged