added validators
tsharon-byte/28_mf_teamwork_01 pull request #4
Opened 2023-07-21 05:33 UTC by ioaksenenko

### Какую задачу решаем
Необходимо добавить валидацию на все формы.
Валидация должна работать по focus/blur событиям и второй раз проверяться при нажатии на submit. 
У валидации должен быть единый механизм: 
- авторизация, 
- регистрация, 
- настройки пользователя.

### Выполненные работы
- добавил правила валидации для полей: email, login, name, password, phone
- добавил валидаторы для форм: login, registration, update-user, chnge-password
- кастомизировал компонент TextField из дизайн системы MUI для возможности передавать правила валидации
- написал компонент Form, с помощью которого можно конструировать формы и передавать валидатор в пропс (валидатор будет срабатывать на событие onSubmit и в случае не валидных данных отклонять запрос)
- написал пример формы в компоненте Home
- покрыл тестами базовый класс валидатора и правила валидации

2023-07-21 12:25 UTC, tsharon-byte approved these changes

2023-07-21 12:25 UTC, tsharon-byte commented on packages/client/src/components/index.ts
> +import Form from './from'
Опечатка в названии директории "from"

2023-07-21 12:25 UTC, tsharon-byte commented on packages/client/src/pages/home/index.tsx
> +    <Form validator={registrationValidator} onSubmit={handleSubmit}>
Может быть вынести пример формы валидации из домашней страницы? Тот, кто будет делать домашнюю страницу перезапишет твой код

2023-07-21 13:38 UTC, tsharon-byte commented
Забыл указать номер задачи в ветке, не смапится автоматически в Linear задачку

2023-07-22 03:21 UTC, Avanire reviewed
Отлично, что все валидаторы покрыты тестами. 

Нужно поправить, форма отправляяется с пустыми полями.

2023-07-22 03:21 UTC, Avanire commented on packages/client/src/pages/home/index.tsx
> +    console.log('success')
Форма отправляется если все поля пустые

2023-07-22 03:31 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
> +    <Form validator={registrationValidator} onSubmit={handleSubmit}>
Написал в домашней странице просто как пример, чтобы одногруппники посмотрели, как это использовать. В отдельный компонент это можно перенести, но по логике тут нужно переносить, например, в страницу регистрации или авторизации. Просто поскольку это задача другого одногруппника, не стал это делать сейчас.

2023-07-22 14:13 UTC, tsharon-byte approved these changes

2023-07-22 16:45 UTC, Olegas requested changes
Добрый день.
Понравилось, как оформили валидаторы и отдельно сами правила.
Есть несколько вопросов по коду, написал их в комментариях.
Нужно доработать.

2023-07-22 16:45 UTC, Olegas commented on lerna-debug.log
> +3 error     at async RegistryFetcher.packument (/home/aio/28_mf_teamwork_01/node_modules/pacote/lib/registry.js:92:19)
Кажется этот файл лишний...

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/components/form/index.tsx
> +      Children.forEach(children, child => {
Код, построенный на использовании Children, может быть хрупким. Например такой подход накладывает жесткие ограничения на верстку форму (вы не можете допустить, что бы среди детей был не компонент формы, а, например, просто div, в котором уже внутри поле).
Доп. материал: https://react.dev/reference/react/Children

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/validation-rules/email-validation-rule/index.ts
> +    return !value || /^[a-z0-9-_.]+@[a-z]+\.[a-z]+$/i.test(String(value))
Совет: в качестве оптимизации - создание регулярного выражения можно вынести за пределы валидатора.

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/validation-rules/password-validation-rule/index.test.ts
> +  it('should return false if more than fourty characters are entered', () => {
А зачем ограничивать пароль сверху?

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/validation-rules/phone-validation-rule/index.ts
> +  validate<T = unknown>(value: T): boolean {
А почему тут unknown? 99.9% тут будет строка или undefined в худшем случае

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/validators/validator/index.ts
> +    return Object.fromEntries(
А в чем прикол? Кажется тут собрали объект ровно той же формы что и был? Почему просто не вернуть this._errors? Если хотите сколнировать что бы снаружи не поменяли, можно пойти через JSON.stringify + JSON.parse или хотя бы написать отдельный метод clone что бы лучше читалось и было понятнее что происходит

2023-07-22 16:45 UTC, Olegas commented on packages/client/src/validators/validator/index.ts
> +    if (!Object.prototype.hasOwnProperty.call(this._errors, fieldName)) {
А зачем нужна такая проверка? Почему просто не проверить через if (!errors[fieldName]) например? Зачем так сложно добираться до hasOwnProperty? Почему просто c this._errors его не позвать?

2023-07-23 14:33 UTC, Olegas approved these changes
Работа принята

2023-07-24 00:40 UTC, merged