redux, router added
tsharon-byte/28_mf_teamwork_01 pull request #46
Opened 2023-08-30 07:26 UTC by likeariverstream

### 28-43 Настроить Redux и Router в SSR

2023-08-31 02:48 UTC, Avanire approved these changes
Отличная работа. Есть замечания, которые надо устранить, чтобы все работало без ошибок на сервере.

2023-08-31 02:48 UTC, Avanire commented on packages/client/index.html
> +    <!--preloaded-state-->
Скрипты лучше подгружать после html

2023-08-31 02:48 UTC, Avanire commented on packages/server/ssr/entry.server.tsx
> +    <ThemeProvider theme={theme}>
Из-за ThemeProvider падает с ошибкой, как ее решить быстро не нашлось, кроме как убрать эту обертку
![изображение](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/60422131/752c283c-e6e9-44f7-bf09-3ec92592b497)

Если убрать эту обертку, следующая ошибка будет связана с localStorage ее можно решить добавив проверку - серверная часть или нет запускает код. Как примерр https://github.com/alex-cory/use-ssr.
![изображение](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/60422131/5eb41b74-2ded-48a2-8f01-f2493dddec5c)

2023-09-01 09:24 UTC, tsharon-byte requested changes
Код не запускается, Пробовала запускать сервер в dev режиме

2023-09-01 09:24 UTC, tsharon-byte commented on packages/server/ssr/entry.server.tsx
> +    <ThemeProvider theme={theme}>
ThemeProvider внутри App уже есть, поэтому из packages/server/ssr/entry.server.tsx его можно безболезненно убрать

2023-09-01 09:25 UTC, tsharon-byte commented on packages/client/index.html
> +    <!--preloaded-state-->
Это как-это?

2023-09-01 09:27 UTC, tsharon-byte commented on packages/client/src/store/index.ts
> +delete window.__PRELOADED_STATE__
Хорошо что глобальная переменная удаляется, не будет утечки памяти

2023-09-01 12:23 UTC, Avanire commented on packages/client/index.html
> +    <!--preloaded-state-->
![изображение](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/60422131/21583b86-4e15-4590-9bee-d3b45bf80583)

вот так от)

2023-09-02 20:05 UTC, likeariverstream commented
Исправил ошибку с запуском, теперь должно нормально работать

2023-09-02 21:23 UTC, likeariverstream commented on packages/server/ssr/entry.server.tsx
> +    <ThemeProvider theme={theme}>
Убрал ThemeProvider

2023-09-03 16:01 UTC, tsharon-byte approved these changes
Сейчас проект собирается и запускается в production режиме

2023-09-03 19:30 UTC, Olegas requested changes
Добрый день.
Есть одна проблема и один вопрос. Написал подробнее в комментариях
Нужно доработать.

2023-09-03 19:30 UTC, Olegas commented on packages/server/db.ts
> +    await client.end()
А зачем отключаться от базы данных? Ведь client затем возвращается из функции и, видимо, предполагается что он будет дальше использоваться

2023-09-03 19:30 UTC, Olegas commented on packages/server/server.ts
> +            `<script>window.__PRELOADED_STATE__ = ${JSON.stringify(
Здесь будет место для XSS. Нужно не забыть корректно заэкранировать состояние приложения. См. подробнее https://redux.js.org/usage/server-rendering#security-considerations

2023-09-04 04:19 UTC, likeariverstream commented on packages/server/server.ts
> +            `<script>window.__PRELOADED_STATE__ = ${JSON.stringify(
Спасибо, исправил)

2023-09-04 04:21 UTC, likeariverstream commented on packages/server/db.ts
> +    await client.end()
Здесь как для примера, наверное, т.к. это код из шаблона. Фактически базу данных еще не используем

2023-09-04 07:01 UTC, Olegas approved these changes
Работа принята

2023-09-04 07:02 UTC, merged