Feature/28 55 forum api client
tsharon-byte/28_mf_teamwork_01 pull request #52
Opened 2023-09-18 13:39 UTC by Avanire

### Какую задачу решаем

Клиент может: - посмотреть все топики, - создать новый топик, - написать комментарий. Все изменения сохраняются в базу данных и доступны после перезагрузки страницы

### Как проверить

Для проверки нужно быть авторизованным через Яндекс OAuth и куки (authCookie, uuid) должны быть в браузере, т.к. запросы спрятаны за миделвар. Можно создать топик, оставить коммент в топике и оставить reply на коммент, все это сохранится в БД

2023-09-20 08:47 UTC, ioaksenenko requested changes
Проделана большая работа. Молодец, хорошо справился.
Есть несколько замечаний, которые надо бы поправить.

2023-09-20 08:47 UTC, ioaksenenko commented on packages/client/.env.development
>  VITE_API_URL='https://ya-praktikum.tech/api/v2'
Вот эту переменную тоже нужно поменять
VITE_API_URL='https://ya-praktikum.tech/api/v2'
на 
VITE_API_URL='http://localhost:3001/api/v2'
иначе вообще не срабатывает авторизация.

2023-09-20 08:47 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Мне кажется текст великоват. Плюс, аватарку выровнять неплохо было бы
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/f0822b44-7242-46d2-af00-17d5d853c9c3)

2023-09-20 08:47 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Тут тоже бы хотя бы отступы добавить слева и сверху или выровнять по центру.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/1eecde54-911e-451f-abcd-e24ffd253714)

2023-09-20 08:47 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Вот тут тоже текст криво смотрится
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/f7c6a42f-0cbe-4a01-84e7-7e14f60f7502)

2023-09-20 08:47 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Не могу ответить на свой ответ. Апи предоставляет такую возможность.

2023-09-20 08:50 UTC, ioaksenenko commented on packages/client/src/components/forum-components/comments-reply-modal/index.tsx
Тут замечания, похожие как на форме создания топика:
- не указано, что поле обязательно для заполения
- если не заполнить и отправить форму, ничего не происходит; не высвечивается сообщение об ошибке

2023-09-21 02:34 UTC, Avanire commented on packages/client/src/components/forum-components/create-topic-modal/index.tsx
В рамках этой задачи было подключение API форума, т.е. я использовал заготовки из прошлых задач, так что верстка не входила в задачи. Предлагаю вынести эту задачу в багфикс

2023-09-21 02:40 UTC, Avanire commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Насчет верстки ответил выше. Тк reply не был сделан в предыдущей задаче, я сделал его сам на быструю руку, и я решил что он будет сделан так) То что можно оставлять reply на reply в api это хорошо, но я не считаю такую реализацию ошибкой

2023-09-21 03:14 UTC, Avanire commented on packages/client/.env.development
Почему то на сервер не приходит инфа через post запрос теперь, хотя все работало. Ищу причину

2023-09-21 12:22 UTC, ioaksenenko commented on packages/client/src/components/forum-components/create-topic-modal/index.tsx
Поле "Описание" в api не обязательно для заполнения, однако на форме почему-то обязательно.

2023-09-21 12:24 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Если перезагрузить старицу, получаем черный экран
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/c1a8f255-6713-45a4-b090-023d74e19974)

2023-09-21 12:25 UTC, ioaksenenko commented on packages/client/src/pages/forum/index.tsx
Если перезагрузить страницу, попадаем на страницу авторизации, хотя по идее был авторизован
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/0dc105b1-c4e3-4d56-b9dd-082e1874d3b8)

2023-09-21 12:29 UTC, ioaksenenko commented on packages/client/src/components/forum-components/comments-reply-modal/index.tsx
Не отображается ошибка в интерфейсе
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/f60c0096-9087-431a-be6f-a7b7c0163005)

2023-09-21 12:32 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Если оставить слишком большой комментарий, тоже не видим ошибку. Со стороны пользователя просто не происходит отправка комментария.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/25799e37-f9e6-42a4-b9b9-27fc41b2a42f)

2023-09-21 12:34 UTC, ioaksenenko commented on packages/client/src/components/topic-components/topic-comment-list/index.tsx
Здесь вместо описания топика вижу свой комментарий
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/3c227655-b8d6-4cf8-a422-ed45bf0c627e)

2023-09-21 12:34 UTC, tsharon-byte commented on packages/client/.env.development
порт видимо должен браться из настроек env для докера
У кого-то он 3000 у кого-то 3001

2023-09-21 12:38 UTC, tsharon-byte commented on packages/client/src/pages/forum/index.tsx
Эта общая проблема в приложении, не связанная с PR
При перезагрузке страницы чистится стор, поэтому useUser() возвращает пустого юзера и редиректит на страницу логина.
Не смотря на то, что юзер затем получен успешно, страница с ProtectedRoute не обновляется и мы видим страницу логина

2023-09-21 12:39 UTC, ioaksenenko commented on packages/client/src/pages/forum/index.tsx
Авторизация через oauth перестала работать. Сначала вроде появляется пользователь, но если обновлю страницу, то он исчезает.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/293c0e37-fe64-410f-8851-bfd4226bb8cb)

2023-09-21 13:18 UTC, ioaksenenko commented on packages/client/src/components/forum-components/comments-reply-modal/index.tsx
Кстати, поле для ответа на сообщение по хорошему бы сделать textarea, а не input. Так просто удобнее.

2023-09-21 13:32 UTC, Avanire commented
А ты не думаешь что будет эффективнее разделить найденые на подзадачи и исправлять их, а не свливать все в один PR?

2023-09-22 02:04 UTC, merged