Feature/28 51 Изменение темы на клиенте
tsharon-byte/28_mf_teamwork_01 pull request #53
Opened 2023-09-18 18:24 UTC by likeariverstream

### Какую задачу решаем
выбор пользователя сохраняется на бэкенде. При следующей загрузке приложения оно загружается с выбранной пользователем темой.

### Как тестировать:
docker compose up, localhost:3001 для приложения, кнопка для изменения темы в хэдере

2023-09-19 05:26 UTC, tsharon-byte requested changes

2023-09-19 05:26 UTC, tsharon-byte commented on packages/server/server.ts
> +  // app.get('/api/theme', express.json(), async (_, res) => {
Здесь точно не забыл удалить комментарий?

2023-09-19 05:26 UTC, tsharon-byte commented on packages/server/db.ts
> +    Theme.sync().then(() => {
Здесь точно не нужен параметр { force: true } ? Если его не указать запись в БД будет каждый раз добавляться насколько я помню

2023-09-19 05:26 UTC, tsharon-byte commented on packages/server/db.ts
>      await sequelize.sync()
Вот эта штука ломает все что написано ниже. 
Просьба использовать имя_модели.sync() вместо этого

2023-09-19 06:27 UTC, likeariverstream commented on packages/server/server.ts
> +  // app.get('/api/theme', express.json(), async (_, res) => {
Забыл, удалил)

2023-09-20 09:08 UTC, ioaksenenko commented on packages/server/db.ts
>      await sequelize.sync()
По моему там ничего не ломается. Таблица Themes создается. Запись там появляется. Что конкретно ломается?

2023-09-20 09:10 UTC, ioaksenenko commented on packages/server/db.ts
> +    Theme.sync().then(() => {
Тут согласен, запись добавляется второй раз, если перезапустить сервер.

2023-09-20 09:13 UTC, likeariverstream commented on packages/server/db.ts
> +    Theme.sync().then(() => {
добавил параметр

2023-09-20 10:14 UTC, ioaksenenko approved these changes
Хорошая работа, молодец.
Есть небольшие замечания в основном по дизайну.
Ещё было бы здорово добавить свой эндпоинт в документацию swagger и покрыть контроллеры тестами.

2023-09-20 10:14 UTC, ioaksenenko commented on packages/client/src/pages/leaderboard/index.tsx
Бронза выглядит слишком черной на светлом фоне
![Uploading image.png…]()

2023-09-20 10:14 UTC, ioaksenenko commented on packages/client/src/pages/login/index.tsx
Кнопки редактирования на странице профиля не видно
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/568cf35f-2810-4179-a90f-a8a97d43711c)

2023-09-20 10:14 UTC, ioaksenenko commented on packages/client/src/pages/login/index.tsx
Кнопку "Изменить" лучше бы сделать ссылкой, как тут
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/624adb03-2327-4e96-9b50-e7e2799db6c9)

2023-09-20 10:14 UTC, ioaksenenko commented on packages/client/src/pages/registration/index.tsx
На форме регистрации кнопка желтая, а в других местах зеленая.
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/e9a35717-e2dd-43d9-9df5-b982395f623f)
Лучше бы сделать единообразно

2023-09-20 10:14 UTC, ioaksenenko commented on packages/client/src/pages/home/index.tsx
Какая-то белая линия слева при светлой теме появляется
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/41943627/d4db542d-b360-43a2-9325-8af8364d7d9e)

2023-09-21 04:45 UTC, tsharon-byte approved these changes

2023-09-21 04:52 UTC, tsharon-byte commented on packages/server/controllers/theme.ts
> +  Theme.create({ mode })
Может здесь лучше использовать Theme.update?

2023-09-21 05:00 UTC, tsharon-byte commented on packages/server/controllers/theme.ts
> +  Theme.create({ mode })
Получается каждый раз новая запись в табл
![image](https://github.com/tsharon-byte/28_mf_teamwork_01/assets/58146989/d1bedaf7-8319-488a-915c-b2b02c803674)

2023-09-21 15:20 UTC, likeariverstream commented on packages/client/src/store/slices/user-slice/types.ts
> +  mode: 'dark' | 'light'
Сделал отдельный тип

2023-09-21 15:22 UTC, likeariverstream commented on packages/client/src/pages/home/index.tsx
Изменил вид кнопок. С белой полосой пришлось поставить background-size, т.к. картинка не оч. подходит

2023-09-21 15:22 UTC, likeariverstream commented on packages/client/src/pages/login/index.tsx
Добавил бордер и изменил вид ссылок

2023-09-21 15:23 UTC, likeariverstream commented on packages/client/src/pages/forum/index.tsx
Как то криво экспортируется из фигмы. Исправил

2023-09-21 15:23 UTC, likeariverstream commented on packages/client/src/pages/leaderboard/index.tsx
Изменил цвет

2023-09-21 15:23 UTC, likeariverstream commented on packages/client/src/pages/registration/index.tsx
Изменил вид кнопки

2023-09-21 15:32 UTC, likeariverstream commented
Исправил замечания по дизайну и добавил эндпойнт в swagger

2023-09-21 17:13 UTC, Olegas commented on packages/client/src/components/profile-components/profile-info/index.tsx
> +  const { user, handleOpenModal, mode, handleUpdateUserSubmit } = props
Совет (не блокирует приемку): mode - очень абстрактно. Режим? Лучше бы назвать theme - тема.

2023-09-21 17:24 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду: 
1. Тема одна на все приложение а не на пользователя? Очень странно
2. При работе с темой и ее переключением есть дублирование кода
Нужно доработать.

2023-09-21 17:24 UTC, Olegas commented on packages/client/src/pages/home/index.tsx
> +  }, [mode])
Вот этот вот набор строк - получение текущей темы и создание функции, которая эту тему переключает - повторяется несколько раз. Я бы вынес это в контекст например, и возвращал из него тему и функцию для переключения. В итоге код переключения и получения значения был бы в одном экземпляре.

2023-09-21 17:24 UTC, Olegas commented on packages/server/models/theme-model.ts
> +  },
А что, тема одна на все приложение? Я себе сменил и у всех пользователей будет такая же?

2023-09-22 13:03 UTC, likeariverstream commented on packages/client/src/components/profile-components/profile-info/index.tsx
> +  const { user, handleOpenModal, mode, handleUpdateUserSubmit } = props
Заменил mode на theme

2023-09-22 13:04 UTC, likeariverstream commented on packages/server/models/theme-model.ts
> +  },
Добавил использование userId для получения и изменения темы

2023-09-22 14:33 UTC, likeariverstream commented on packages/server/models/theme-model.ts
> +  },
Исправил, добавил изменение с использованием userId

2023-09-23 13:51 UTC, Olegas requested changes
Стало лучше, но теперь появились другие проблемы. Написал по ним подробные комментарии.

2023-09-23 13:51 UTC, Olegas commented on packages/server/models/theme-model.ts
> +  },
Если мы ищем тему по пользователю, то нам нужен индекс по этому полю. И индекс этот надо сделать уникальным - иначе возможно сохранение нескольких записей для одного пользователя. Еще очень странно что это поле может быть null. Что это за запись - без указания пользователя? Что она онзначает?

2023-09-23 13:51 UTC, Olegas commented on packages/server/controllers/theme.ts
> +        })
Такой подход (поискать, если нет - создать, если есть - обновить) - сломается при конкурентных запросах. Два запроса придут и обнаружат, что тема не установлена. Оба пойдут создавать и либо вставят дубль, либо один наткнется на нарушение уникального индекса (про индекс написал отдельный комментарий). Тут лучше использовать подход под названием upsert

2023-09-23 13:51 UTC, Olegas commented on packages/server/db.ts
> +    })
А зачем теперь нам эта конструкция? Зачем вставлять в базу тему для никакого пользователя?

2023-09-23 20:39 UTC, likeariverstream commented on packages/server/db.ts
> +    })
Удалил этот код

2023-09-23 20:39 UTC, likeariverstream commented on packages/server/controllers/theme.ts
> +        })
Изменил на upsert

2023-09-23 20:39 UTC, likeariverstream commented on packages/server/models/theme-model.ts
> +  },
Добавил параметр unique, установил allowNull: false

2023-09-24 08:42 UTC, Olegas approved these changes
Отлично! Работа принята. Спасибо.

2023-09-25 18:28 UTC, merged