28-27: Создать механику игры на Canvas API. Часть 5: анимация.
tsharon-byte/28_mf_teamwork_01 pull request #9
Opened 2023-07-24 09:05 UTC by tsharon-byte

### Какую задачу решаем
28-27: Создать механику игры на Canvas API. Часть 5 : Анимация.
Добавлен класс Sprite для работы со спрайтами и показан пример работы с классом.

### Скриншоты/видяшка (если есть)

### TBD (если есть)
Реализовать остальные части механики игры (с 1го по 4ый)
Сейчас на роут игры можно попасть без авторизации. Поправить после добавления авторизации

2023-07-24 15:12 UTC, likeariverstream approved these changes
Создан класс Sprite для работы со спрайтами и добавлен пример работы.
Все отлично работает, в т.ч реакция на упраление

2023-07-24 15:12 UTC, likeariverstream commented on packages/client/src/pages/game/index.tsx
> +      // @ts-ignore
Использование @ts-ignore не рекомендуется, можно убрать ошибки, если немного изменить класс Sprite [примерно так](https://www.typescriptlang.org/play?ts=4.7.4#code/C4TwDgpgBAymBOBLYEDyZiIPYDsDOUAvFAN4BQUUAxsAB4BcUAwgIY4BuLeAShDgCYQkOAOZNcKWsABMAESgAfKDgCuAGzUUoiALYsRERqw5cAknoMwsK+FQhbMVANZ4ACkIBi8FjsPKVOgBGQlqqQUKoAGZePhB4jGHB8FoA7oj8wAAWCQFJWpkQiCKZwDnhyZR4iABefokhlIEsziLw1gKMeMDCIlq0AAwA-GV5lCBDIyEAvmRkVLhdUB7cAIIAsgCiAPoAEhumAOI7ACpEUAAsAByzVGpcBHBIKKRaCIiczzQMzGycPHyCHriHCSGTyJSqDSvJAfaDwCAsfi4NQgbQWPzGP7mfQQKw2OzQ94sZ6Rby+UwCCDfeoVKBvWFQRxOcQqEGTWn04lwhFInAoxmIZxuTxkuq5Bp0mFcqDwxHI1E0qIxXzxfzlQkM2W8-lpDLZNWjSVE55a+VQApFErsjXS+EARxUcWApn47MUUFZgkiiBwEH4NueXRY8BQrqggSwWDUCJwAe5cr5qKqtWtlE5Jp5ZqaLTans63R9vTTUozCf5A1TRs1mcTUHGlfT0DwIGtWnm+G6KhoWHgAAosBhsPhGI9kGhBwsAJQvSiULKIPAAOi+ZwHmAWy7os1njMyC8Xuhxq4n+AP6O3s-nS9JsQpgloZ36Wjne6XTJZIMfz93+6ZwvgyrQMQa5Dm+gouO4AGiooShPjuV6Loq0SigQwEnkuSGAQQChKAAjBeL77rqWTHuup7EZk34IRaxTAKRoGLjRJRUa+i72o6XQumcnoQN6vr+vBrFBiGfpnJELBqHg9iCfuyZAVAIEbnJLH7gM9EbmpOFQHBl6seM6mnvpWk6YRS7Nl+MlLtmTitO0-AGVZzQ2bmAgqUuaiRmAZwIR5A6LoEPr8L2V6Tm5jFsPw0YANIQCAshYCkODeaxmQRdFsXxYl-mBcFr6hZQMxaCoYD8FyvbTuQlmLu+7TAAA1HVBHaJEUC5b+4EfnRAB8P5gUKkGARV36mdVHW1RZO7Na1CE3uSlIPgAPL1iHivASooVAAC0UC4UNk26fus0QHeVINcNUBTFAECSdAlX7ctR0nQ+xAmbOMw7u9F0XvClJ9nts6IC1vYAIQIV8-07vCwA2LGH1hV8i7ehoMCgNGyX7tZtmevDdCI4gGi8DQvbnQhclQHVy0DAANCTQk1NAFMIeMNP7aT9Ms5NbO1N++UHUuCP8N4KTYgYxOs6xh4GBzO5tdeopPVAABUy0UdOAD0y2YSh0t84uzY6yNFFQBrCFa7EeAG8tTHAJbXMM5T-S23TtTk8tzO07J7Me2Z9M81ohWUKlAjpXFCVJcQvZ+DFIARsG-AbOwfDANOhA9XdlCA61ECLk4sVEIQxAAOTcJawCFzBV053nBdFys8BtCkJe0YXEO6+ZxDLOs2x7IcJxK1AADM36XddUlTZHVeojXUCFwAMrxZcV9nudTwXM91w38+RGXrcje3SyrJsuz7EcxzD1dN3j8v1dr4XACqYDl1p1+r7X9cJQ-LczpzQlTwfXfH17qcZW0hz6j2gJnCeK985F0yjgJ+SgX4wPXu-FIcCv7pzbn-V6n0A5QF8l5COKc07fkgaTYAwZQy72WsVUqKByrezYgCIQDD9ppAEAlJhDonQrBwIeMigFZaLgIbzAq-sLzCWAOVb+e8KEiXssQTs0kAZA1BqxdiToXTUIQhoziCioDsKRCkLhHFgC8P4UOQRPlPKiNnEiKgAQk6LkRPHROIJZ4LhQL6PshcV5GPgVTK2aUIDRzgYE8SN1bG4IkcAAc0jMHkMoaJYgESpKkKBjoiA3C9HUMMZwqgbA7BqHMXoARoohG6OdPwWxI1KlcWIDxPifpzr2McSCJhOgsCJwTknDxXQ+AsN8bFfxhdAnUWCaEsOUTxGFSpGAHsdEvQsHUHRUcKBZhAA) и функцию Game [примерно так](https://www.typescriptlang.org/play?ts=4.7.4#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecBiAwtgK4DOSAogGbVIakXLWNIDKMKMScAvnNSgQQcAORRUGUQChQkWGIB0AegDiKEEkVoyZGXOjw2YKMG4ChI0YpU3lJGMAA2ZZcdPcZ0tBAB2ZeDJgAC8eAF44AGYAJm8-ALgAd2AAExgACzgIyIBGOP94dKRgAHN0+AicyPyEgCFKABUGgE0AfTYABQQASQbKLLFQEuUAIyQYGABPRTBfEpkfArh6pubo9q7e-ojRIdHxqeiZuYX4+FVKAHkEC4HdkGGSpGgn4-ma+AB1AEEAGV+7ntHE4kK1EignE43l5Fgl1JoAFwEQgDAAUAEosgA+XDSOBwWHwCTUAbkJDMAA8AAkGgBZX6EFC+ABuKDIlBBml8MCxqN8JEh6LxcBB8BGwjGUCR7jMPAAPnASL4UkhqMBfEgUsLRXBxSBJdFpSZZXAFUqVWqNVr8Tq9ZLIkaPPLFcrVerNdJhYS4CkoChErUJUgoGiyFA0EiAqY5tgAB4ABgG8ewk0TEXjmLCOJwwvx3p86u6IBQTwGGsScCLJaQGNzBIgheLrzDaAGLbrwBJqOJ2hIUAk3MxOfxI7gEhgfd8cHLcBl3FRw9HI4wsaRPbQfYHMEUTxghD83FjMFRomiKVE6MwddHoGrSILvirTyvS5HyTS6SROQAnNEX6+4CKUpyiRABWZNrxHfl9WDS5qHwP1NDIJEABZ-1fRw0AAazIDpgwQjQkCRSIIIAuAglCdClxGdAsJKIRzSRUQAGJ4zY9jRCo0cEy4kdU143ghVHXhhREr0zh9P0A2gFUQwiDFsVxG8uwAQnXTckEHJSl3HSc6xE0d8xgWMBnU-tNO3Xd925JAjxPM8Lzrb1b1LCIZyfGshJHFytBbAYfn+T0bybLQ-CcCAUBSAZqCVDBgD8OAFJzSDO0SlSVyHSD8V0qBfEggyl29cUoFkjouG4XKBhXbQJC4JAyomYNfFRHzsHEJAwFQGBHNfVLURU4rSvKprMrInK8tfArDOMxQ1UhDhJhBAZBuDBqKompdlGUOAADkIArX1-XIwi4AgEYACt6BgZCBGAKAEhQMcrqZEoQUg6q5qcZAMFRZM4D+iieAAKkS98MjgABqOBokvciQmBxKgLKeAoZhrzptjWbnCcBalp2Vj2LYmRXw+7HvuPQHsEpuHQjgEGwfSKn4bpwDimR9G+FEoLFQoGg6B+hSs20-E+rMrdRqXQ7pJK4Na1fO1gwGKXAxgqBURWFoNh6PoOfxBWoGiJWpJVyV1caFp1k6bXKCZyj-t13UgygSIjf9E3ZYua4LltpAfY5greGwABtABdIVxKWAIUFgeFwkSzNsw7Lt9Yl0d9cUKPYDlkcprgPr9Zh4WRwLjPOCz-2k8S-XIlT4unciUvo+PCv8QK70AggMBY7RBOi-zp3a71p3S877PW8r1EC8Hx3VaODuwDHznlKr+vp+rkeF5bkctpSCANy5bdwrQLh4t8RQJHCyKMQAbi57LxknRLufxCkUmAZkCScNkyB2wiwgAIhKIRf+WJIIUmPiyNkWUnrUDCDgYkudRwMzgYDFmqIGaQ2huiRBI4kblBQczEGqI8EoywTg5QoDXyv3fp-b+v9NAAKAZoVoIwHAwHiCA6BFJWETASn4QgThgDYRQWXGAsdeBYkALgggAGEEAOIg0jABCIIAGRA4CAAwQQAzCCAAEQQAwiAUlGGwvwlCALcIMVOfhgjhE4HnuIrEgA8EEAFwggA+EEALwgsjAAcIMotRWjdH6N4b4Ixo49Fv2ZAEuAQT35GKFCJWy8h4AWhQAKc4hFpBAA)

2023-07-25 05:12 UTC, ioaksenenko requested changes
Хорошая работа, молодец!

Есть несколько некритичных замечаний к оформлению кода и структуре файлов.

2023-07-25 05:12 UTC, ioaksenenko commented on packages/client/src/utils/Sprite.ts
1. Лучше бы вынести типы и константы в отдельные файлы, чтобы соответствовать общей структуре приложения.
2. Где-то используются стрелочное определение методов, где-то традиционное. Мне кажется, лучше привести к единому стилю.
3. Неплохо было бы добавить тесты для класса Sprite

2023-07-26 11:52 UTC, tsharon-byte commented on packages/client/src/utils/Sprite.ts
поправила, тесты добавлю когда будет написана механика игры

2023-07-26 11:52 UTC, tsharon-byte commented on packages/client/src/pages/game/index.tsx
поправила

2023-07-26 14:13 UTC, ioaksenenko approved these changes

2023-07-26 17:42 UTC, Olegas requested changes
Хорошая работа!
Написано понятно и читабельно.
Персонажи милые )
Но есть один важный архитектурный момент - описал его в комментарии к коду. 
Нужно доработать.

2023-07-26 17:42 UTC, Olegas commented on packages/client/src/components/bomberman/index.tsx
> +  let bomber3: Sprite | undefined
Для bomber, bomber2 и bomber3 надо использовать стейт или ref. Потому что иначе при каждом рендере компонента переменные будут заново создаваться и не будут проинициализированы.

2023-07-26 17:42 UTC, Olegas commented on packages/client/src/utils/Sprite.ts
> +    this.loop = this.loop.bind(this)
А это точно нужно? this.loop это свойство, в котором лежит стрелочная функция. Разве ей надо контекст привязывать?

2023-07-26 17:42 UTC, Olegas commented on packages/client/src/utils/Sprite.ts
> +    this.handleKeyDown = this.handleKeyDown.bind(this)
Тот же вопрос что и про this.loop

2023-07-26 17:42 UTC, Olegas commented on packages/client/src/utils/Sprite.ts
> +      document.addEventListener('keydown', this.handleKeyDown, false)
Вот здесь архитектурно странно получилось. Спрайт знает о клавиатуре и конкретных кнопках, которыми он управляется.
Представь следующие ситуации:
1. Решили сменить кнопки, которыми управляется персонаж
2. Решили сделать игру для двух игроков с одной клавиатуры (один играет на стрелочках а другой на WSAD)
3. В игре появились "враги" которыми управляет программа и они сами ходят по карте (на при этом они тоже анимированные).

Любой из этих сценариев все сломает и придется лезть в код класса Sprite.
Архитектурно правильно - вынести аспект управления из спрайта и оставить ему только анимацию.

2023-07-29 06:29 UTC, Olegas approved these changes
Отличная работа! Принято.

2023-07-29 07:39 UTC, merged